#https://github.com/felipewom/docker-compose-postgres
services:
  righten:
    build:                ./Web/
    restart:              always #might be bad choice
    command:              sh -c "sleep 10s ; python3 ./run.py" #Waiter script
    ports:
      - 5000:5000
    stop_signal:          SIGINT     #flask requirement
    environment:
      FLASK_SERVER_PORT:  '5000'
    volumes:
      - ./Logs:/logs
    depends_on:
      - rightendb
  
  #FIXME: Currently refuses connection from pgadmin, need to connect app
  rightendb:
    build:                ./Database/
    restart:              always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER:      postgres # The PostgreSQL user (useful to connect to the database)
      POSTGRES_PASSWORD:  postgres # The PostgreSQL password (useful to connect to the database)
      POSTGRES_DB:        RightenDB # The PostgreSQL default database (automatically created at first launch
    #Share folder with container to persist data
    volumes:
      - ./Database/RightenDB/:/var/lib/postgresql/data/
      #Initialize data first time container is run
      - ./Database/Righten_mock-sqlite_dump.sql:/docker-entrypoint-initdb.d/init.sql
    
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - "5050:80"